### ISSUE TITLE
compiling, headers missing 

### ISSUE THREAD

**Issue by frehberg** [eclipse/titan.core#121]
Trying to compile titan.core first time using "make", the following header files are not found, but compilation-process continues. 
Repeating the build process calling "make" second time, the error no longer shows up.

Two issues:
1) The compilation-process should be interrupted in case of errors.
2) It seems the error shows up, because the source-files depend on header-files not generated yet. It seems the file  core/Makefile lacks source-header dependencies. All headers should be generated before compiling the source files.

Notify: Parsing TTCN-3 module `TitanLoggerControl.ttcn'...
Notify: Checking modules...
Notify: Generating code...
Notify: File `RT1/TitanLoggerControl.hh' was generated.
Notify: File `RT1/TitanLoggerControl.cc' was generated.
Notify: 2 files were updated.
touch RT1/TitanLoggerControl.cc.compiled
  (dep)  TitanLoggerControlImpl.cc
In file included from RT1/TitanLoggerControl.hh:19:0,
                 from TitanLoggerControlImpl.cc:15:
./TTCN3.hh:77:10: fatal error: RT1/TitanLoggerApiSimple.hh: No such file or directory
 #include "RT1/TitanLoggerApiSimple.hh"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
  (dep)  XmlReader.cc
  (dep)  XER.cc
  (dep)  Verdicttype.cc
  (dep)  Universal_charstring.cc
  (dep)  Param_Types.cc
In file included from Param_Types.cc:37:0:
Debugger.hh:23:10: fatal error: RT1/PreGenRecordOf.hh: No such file or directory
 #include "RT1/PreGenRecordOf.hh"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
  (dep)  Timer.cc
  (dep)  Textbuf.cc
  (dep)  TEXT.cc
  (dep)  Template.cc
  (dep)  Struct_of.cc
  (dep)  Snapshot.cc
  (dep)  Single_main.cc
Single_main.cc:39:10: fatal error: TitanLoggerApi.hh: No such file or directory
 #include "TitanLoggerApi.hh"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
  (dep)  Runtime.cc
  (dep)  RAW.cc
  (dep)  Port.cc
Port.cc:49:10: fatal error: TitanLoggerApi.hh: No such file or directory
 #include "TitanLoggerApi.hh"
          ^~~~~~~~~~~~~~~~~~

**Comment by erititan** [comment]
Hi Frank, 
this is non-issue,  as you noticed, the files missing in this phase will be generated later, the compilation succeeds eventually.
