### ISSUE TITLE
Problem with TestPort IPL4asp using SSL

### ISSUE THREAD

**Issue by ov3rlord4** [eclipse/titan.core#147]
I've faced a problem using the above testport. I'm setting a SSL server and I need to find out whenever a new connection is opened. So I was waiting in an alt statement the ASP_Event message, unsuccessfully. Investigating in the file **IPL4asp_PT.cc** I found out a weird if statement at line 1204. In the comment above the statement saying "if SSL is also triggered, we will report the connOpened at the end of the handshake". Then I tried to find that point of the code, unsuccessfully (again). So I just tried to remove the if (i.e. calling the function reportConnOpened every time) and it worked! I suppose that removing it is not a problem because the handshake should be already completed since it is performed in the function **starttls**. Did I properly fix it?

**Comment by ethgasz** [comment]
For the first look the proper if statement :
    if(sockList[connId].ssl_tls_type == NONE || sockList[connId].sslState = STATE_NORMAL;) {
      reportConnOpened(k);
    }

**Comment by ov3rlord4** [comment]
It works fine. Thank you.
